version: '3.8'

services:
  ros2-dev:
    image: ros2_workspace:latest
    container_name: ros2-dev
    hostname: ros2-dev
    
    # 网络配置
    network_mode: "host"
    
    # 环境变量
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - ROS_DOMAIN_ID=0
      - ROS_LOCALHOST_ONLY=0
      
    # 卷挂载
    volumes:
      # 工作空间挂载
      - ./ros2_ws:/home/vscode/ros2_ws
      # X11 显示
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      # 可选：Git 配置
      - ~/.gitconfig:/home/vscode/.gitconfig:ro
      # 可选：SSH 密钥
      - ~/.ssh:/home/vscode/.ssh:ro
      
    # 设备访问（可选）
    devices:
      - "/dev/dri:/dev/dri"  # GPU 加速
      - "/dev/ttyUSB0:/dev/ttyUSB0"  # 串口设备
      - "/dev/ttyACM0:/dev/ttyACM0"  # 串口设备
      
    # 权限
    privileged: true
    user: "vscode"  # 使用您创建的开发用户
    
    # 保持运行
    stdin_open: true
    tty: true
      
    # 自定义命令
    command: >
      bash -c "
        sudo /usr/sbin/sshd &&
        echo 'SSH 服务已启动.' &&
        echo '正在执行工作控件初始化脚本 init script...' &&
        bash /home/vscode/ros2_ws/init.sh &&
        echo '---' &&
        echo 'ROS2-Dev 容器已经启动' &&
        echo '通过SSH连接: ssh vscode@localhost (password: password)' &&
        tail -f /dev/null
      "